name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Explicitly grant write access

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Check if repositories.txt has changed
      id: check_changes
      run: |
        git diff --quiet HEAD^ HEAD repositories.txt || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Check if README.md exists
      id: check_readme
      run: |
        if [ -f README.md ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Ensure README exists
      if: steps.check_readme.outputs.exists == 'false'
      run: |
        echo "README.md does not exist. Creating a new one."
        touch README.md

    - name: Set up Python
      if: steps.check_changes.outputs.changed == 'true' || steps.check_readme.outputs.exists == 'false'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: steps.check_changes.outputs.changed == 'true' || steps.check_readme.outputs.exists == 'false'
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub humanize

    - name: Run Python script to update README
      if: steps.check_changes.outputs.changed == 'true' || steps.check_readme.outputs.exists == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GITHUB_TOKEN is passed
      run: python update_readme.py

    - name: Commit changes
      if: steps.check_changes.outputs.changed == 'true' || steps.check_readme.outputs.exists == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Create or Update README"
        git push
