name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Updated to v3 for Node 16 compatibility
      with:
        fetch-depth: 2  # Fetch the last two commits to compare changes

    - name: Check if repositories.txt has changed
      id: check_changes
      run: |
        git diff --quiet HEAD^ HEAD repositories.txt || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Set up Python
      if: steps.check_changes.outputs.changed == 'true'
      uses: actions/setup-python@v4  # Updated to v4 for Node 16 compatibility
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub humanize

    - name: Run Python script to update README
      if: steps.check_changes.outputs.changed == 'true'
      run: python update_readme.py

    - name: Commit changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update README"
        git push
